// Generated by LiveScript 1.2.0
(function(){
  var MyRobot, tr;
  var judge;
  judge=0;
  importScripts('../base-robot.js');
  MyRobot = (function(superclass){
    var prototype = extend$((import$(MyRobot, superclass).displayName = 'MyRobot', MyRobot), superclass).prototype, constructor = MyRobot;
    prototype.doSearch = function(){
      this.turn_turret_right(270);
    };
    prototype.chase_left = function(){
        this.turn_turrent_left(15);
    };
    prototype.chase_right = function(){
        this.turn_turrent_right(15);
    };
    prototype.runaway = function(){
        var a = Math.random()%2;
        var angle = this.me.angle%360;
        if(angle>=180){
           this.turn_right(90);
           this.turn_turret_left(90);
        }
        else{
           this.turn_left(90);
           this.turn_turret_right(90);
        }
        if(a){ 
            this.move_forwards(50);
        }
        else{
            this.move_backwards(50);
        }
        
        
    };
    prototype.onIdle = function(){
      var myAngle, forward, tinyMove, tinyShoot, leftDist, rightDist;
      this.idleCount++;
      myAngle = this.me.angle % 360;
      if (this.myVarEnemy) {
        forward = false;
        tinyMove = Math.random() * 45;
        tinyShoot = Math.random() * 10;
        leftDist = myAngle + 360 - this.myVarEnemy[0].angle;
        if (leftDist > 360) {
          leftDist = leftDist - 360;
        }
        rightDist = this.myVarEnemy[0].angle - myAngle;
        if (rightDist < 0) {
          rightDist = 360 + rightDist;
        }
        if (leftDist !== rightDist) {
          if (Math.random() > 0.5) {
            forward = true;
          }
          if (leftDist > rightDist) {
            this.turn_turret_right(rightDist + 5 + tinyShoot);
          } else {
            this.turn_turret_left(leftDist + 5 + tinyShoot);
          }
          if (forward) {
            this.move_forwards(tinyMove);
          } else {
            this.move_backwards(tinyMove);
          }
          this.shoot();
        } else {
          this.shoot();
        }
        this.myVarEnemy = undefined;
      } else {
        if (this.idleCount > 3) {
          this.doSearch();
          if (this.idleCount > 4) {
            this.doSearch();
            if (this.idleCount > 5) {
              this.doSearch();
            }
          }
          return;
        }
        this.turn_turret_left(30);
        this.turn_left(30);
        this.move_forwards(Math.random() * 50 + 10);
      }

        judge--;
    };
    prototype.onWallCollide = function(){
      this.move_opposide(10);
      this.turn_left(90);
    };
    prototype.onHit = function(){
      this.runaway();
      this.yell("Splendid, Brother!");
    };
    prototype.onEnemySpot = function(){
      this.yell("Show me what you got, SNAKE!!");
      this.shoot();
      this.shoot();
      judge++;
      if(judge>=2){
        this.chase_left();
      }
      else{
        this.chase_right();
      }
    };
    function MyRobot(){
      MyRobot.superclass.apply(this, arguments);
    }
    return MyRobot;
  }(BaseRobot));
  tr = new MyRobot("Liquid");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
